# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9c4590b91307326a819987ec38d61c9bb0a8e7d26eb4b0b6d6a2454b38b7d64b846b8c17e02230b4cd81dfa13cbc47d53d3b0275dd79a70f2bea51fffe4d115b

test:
  secret_key_base: 33bd3f5c750cd1ef9937cb981af862047cfcab1d78cef676d4db3db159e7bc0848c7f56491136ce2aa24191971b72bc12c56bb3c0bccfde943b55cb6a69dd422

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
